trigger:
- master

jobs:
- job: clang_format
  pool:
    image: 'ubuntu-16.04'
  steps:
    - script: |
        llvm_release=clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04
        llvm_tarball=$llvm_release.tar.xz
        wget -q https://releases.llvm.org/7.0.1/$llvm_tarball
        tar xf $llvm_tarball
        export PATH=$PWD/$llvm_release/bin:$PATH
        clang-format --version
        dev/check-fmt

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      gcc:
        CC: 'gcc'
        CXX: 'g++'
      clang:
        CC: 'clang'
        CXX: 'clang++'
  steps:
  - script: |
      env REBAR_COLOR=low rebar3 compile
      env REBAR_COLOR=low rebar3 eunit

- job: Linux_Debug
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      gcc:
        CC: 'gcc'
        CXX: 'g++'
      clang:
        CC: 'clang'
        CXX: 'clang++'
  steps:
  - script: |
      env RE2_DEBUG=1 REBAR_COLOR=low rebar3 as debug compile
      env RE2_DEBUG=1 REBAR_COLOR=low rebar3 as debug eunit
      dev/l.sh 128

- job: Dialyzer
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: env REBAR_COLOR=low rebar3 dialyzer

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      brew install erlang
      make clean test

- job: Windows_VS2017_NMake
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco install --no-progress erlang rebar3
      @call "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
      env REBAR_COLOR=low CMAKE_GENERATOR='NMake Makefiles' DEBUG=1 rebar3 compile
      ls -lh re2/obj/re2.lib
      ls -lh priv
      find . -name re2_nif.dll
      file priv/re2_nif.dll
- job: Windows_2016_MinGW_vcvars
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco install erlang rebar3 mingw
      @call "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
      env REBAR_COLOR=low CMAKE_GENERATOR='MinGW Makefiles' DEBUG=1 rebar3 compile
      ls -lh priv
      find . -name re2_nif.dll
      file priv/re2_nif.dll
- job: Windows_2016_MinGW
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco install erlang rebar3 mingw
      env REBAR_COLOR=low CMAKE_GENERATOR='MinGW Makefiles' DEBUG=1 rebar3 compile
      ls -lh priv
      find . -name re2_nif.dll
      file priv/re2_nif.dll
- job: Windows_2016_MSYS
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco install erlang rebar3 msys2
      env REBAR_COLOR=low CMAKE_GENERATOR='MSYS Makefiles' DEBUG=1 rebar3 compile
      ls -lh priv
      find . -name re2_nif.dll
      file priv/re2_nif.dll
- job: Windows_2016_MSYS2
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco install --no-progress erlang rebar3 msys2
      env REBAR_COLOR=low RE2_MSYS2=1 DEBUG=1 rebar3 compile
      ls -lh re2/obj/libre2.a
      ls -lh priv
      find . -name re2_nif.dll
      file priv/re2_nif.dll
- job: Windows_VS2017
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco install --no-progress erlang rebar3
      @call "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
      env REBAR_COLOR=low CMAKE_GENERATOR='Visual Studio 15 2017' DEBUG=1 rebar3 compile
      ls -lh c_src/re2/windows_build/Release/re2.lib
      ls -lh priv
      find . -name re2_nif.dll
      file priv/re2_nif.dll
